title: Conditions and Cycles
description: Open source, Kubernetes, Monitoring
author: Daniel Šintaj 
github: https://github.com/xdnny
about: DevOps engineer
disqus_shortname: xdnny-github-io
google_analytics: UA-155196693-1

enableTags: true
tagarray: [kubernetes,python]

social:
  - icon: fa-twitter
    link: "https://twitter.com/DanielSintaj"
  - icon: fa-github
    link: "https://github.com/xdnny"

url: "https://xdnny.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
